[package]
name = "floater"
version = "0.1.0"
authors = ["Do Duy <juchiast@gmail.com>"]

[dependencies]
stdweb = "0.4.7"
yew = { git = "https://github.com/DenisKolodin/yew", rev = "f077a9a" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
